In [1]:
# import stuff
#General

#My Code
import io_manager as io
import plot_moments
from pars_shocks import Pars
import my_toolbox as tb

main_path = "C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/"
trans_path = main_path + "input/MH_trans/"
out_path = main_path + "trans_output_test/"
myPars = Pars(main_path, J=51)


In [2]:
trans_name = "MH_trans_by_MH_clust_k2_age"
dis_trans_path = trans_path + trans_name + ".csv" 
myPars.H_trans = io.read_and_shape_H_trans_full(myPars, dis_trans_path)
plot_moments.plot_H_trans_H_type(myPars, out_path, trans_name) 

trans_name = "MH_trans_by_MH_clust_50p_age"
dis_trans_path = trans_path + trans_name + ".csv" 
myPars.H_trans = io.read_and_shape_H_trans_full(myPars, dis_trans_path)
plot_moments.plot_H_trans_H_type(myPars, out_path, trans_name) 


In [3]:
trans_name = "MH_trans_uncond_age"
dis_trans_path = trans_path + trans_name + ".csv" 
my_trans = io.read_and_shape_H_trans_uncond_age(myPars, dis_trans_path)
# print(my_trans)
myPars.H_trans = my_trans
# print(myPars.H_trans)
plot_moments.plot_H_trans_uncond(myPars, out_path, trans_name) 

In [4]:
trans_name = "MH_trans_uncond"
dis_trans_path = trans_path + trans_name + ".csv" 
myPars.H_trans = io.read_and_shape_H_trans_uncond(myPars, dis_trans_path)
trans= myPars.H_trans[0,0,:,:]
io.print_H_trans_to_tex(myPars, trans, out_path, trans_name)

trans_name = "MH_trans_by_MH_clust_k2"
dis_trans_path = trans_path + trans_name + ".csv" 
myPars.H_trans = io.read_and_shape_H_trans_H_type(myPars, dis_trans_path)
for type_ind in range(myPars.H_type_perm_grid_size):
    if type_ind == 0:
        type_name = "low"
    elif type_ind == 1:
        type_name = "high"
    lhs_tex = f"\\Pi_{{H}} \\left( u_{{H,k=2}} = \\text{{{type_name}}} \\right)"
    
    trans= myPars.H_trans[type_ind,0,:,:]
    my_nf_name = trans_name + f"_{type_ind}"
    io.print_H_trans_to_tex(myPars, trans, out_path, my_nf_name, tex_lhs_of_equals = lhs_tex)

trans_name = "MH_trans_by_MH_clust_50p"
dis_trans_path = trans_path + trans_name + ".csv" 
myPars.H_trans = io.read_and_shape_H_trans_H_type(myPars, dis_trans_path)
for type_ind in range(myPars.H_type_perm_grid_size):
    if type_ind == 0:
        type_name = "low"
    elif type_ind == 1:
        type_name = "high"
    lhs_tex = f"\\Pi_{{H}} \\left( u_{{H,50p}} = \\text{{{type_name}}} \\right)"
    
    trans= myPars.H_trans[type_ind,0,:,:]
    my_nf_name = trans_name + f"_{type_ind}"
    io.print_H_trans_to_tex(myPars, trans, out_path, my_nf_name, tex_lhs_of_equals = lhs_tex)


PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/MH_trans_uncond.pdf
PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/MH_trans_by_MH_clust_k2_0.pdf
PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/MH_trans_by_MH_clust_k2_1.pdf
PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/MH_trans_by_MH_clust_50p_0.pdf
PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/MH_trans_by_MH_clust_50p_1.pdf


In [5]:
r2_path = trans_path + "MH_type_reg_r2.csv"
my_r2_mat = tb.read_matrix_from_csv(r2_path, column_index = 0)
print(my_r2_mat)
io.table_r2_by_type_alg(myPars, my_r2_mat, out_path, "tab_MH_type_reg_r2")

[[0.36683968 0.36397704 0.4072378  0.45254377 0.47089562        nan]
 [0.3753773  0.37627357 0.41752702 0.45815882 0.47603071 0.07205222]]
PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/tab_MH_type_reg_r2


In [6]:

trans_name = "MH_trans_by_MH_clust_50p"
dis_trans_path = trans_path + trans_name + ".csv" 
trans_50p = tb.read_matrix_from_csv(dis_trans_path, column_index = 0).reshape(2,2,2)
print(trans_50p)

trans_name = "MH_trans_by_MH_clust_k2"
dis_trans_path = trans_path + trans_name + ".csv" 
trans_k2 = tb.read_matrix_from_csv(dis_trans_path, column_index=0).reshape(2,2,2)
print(trans_k2)

io.table_H_trans_by_type_alg(myPars, trans_50p, trans_k2, out_path)

[[[0.75270027 0.24729975]
  [0.53708732 0.46291265]]

 [[0.20334896 0.79665107]
  [0.10277858 0.89722145]]]
[[[0.85517973 0.1448203 ]
  [0.71741933 0.28258064]]

 [[0.38501057 0.6149894 ]
  [0.16947505 0.83052498]]]
PDF successfully created at C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/MH_Model/my_code/model_uncert/trans_output_test/H_trans_by_type_alg_test.pdf
