In [87]:
# import stuff
# my code
import model_no_uncert as model
import my_toolbox as tb
from pars_shocks_and_wages import Pars, Shocks
import plot_lc
import run
import simulate
import solver

# general
import numpy as np

In [109]:
main_path = "C:/Users/Ben/My Drive/PhD/PhD Year 3/3rd Year Paper/Model/My Code/Main_Git_Clone/Model/My Code/my_model_2/output/"

# my_lab_FE_grid = np.array([10.0, 20.0, 30.0, 40.0])
my_lab_FE_grid = np.array([10.0, 20.0, 30.0])
lin_wage_coeffs = [0.0, 0.5, 0.5, 0.5]
quad_wage_coeffs = [-0.000, -0.020, -0.020, -0.020] 
cub_wage_coeffs = [0.0, 0.0, 0.0, 0.0]

num_FE_types = len(my_lab_FE_grid)
w_coeff_grid = np.zeros([num_FE_types, 4])
    
w_coeff_grid[0, :] = [my_lab_FE_grid[0], lin_wage_coeffs[0], quad_wage_coeffs[0], cub_wage_coeffs[0]]
w_coeff_grid[1, :] = [my_lab_FE_grid[1], lin_wage_coeffs[1], quad_wage_coeffs[1], cub_wage_coeffs[1]]
w_coeff_grid[2, :] = [my_lab_FE_grid[2], lin_wage_coeffs[2], quad_wage_coeffs[2], cub_wage_coeffs[2]]
#w_coeff_grid[3, :] = [my_lab_FE_grid[3], lin_wage_coeffs[3], quad_wage_coeffs[3], cub_wage_coeffs[3]]

print("intial wage coeff grid")
print(w_coeff_grid)

myPars = Pars(main_path, J=50, a_grid_size=5, a_min= -500.0, a_max = 500.0, lab_FE_grid = my_lab_FE_grid,
            H_grid=np.array([0.0, 1.0]), nu_grid_size=1, alpha = 0.45, sim_draws=1000,
            wage_coeff_grid = w_coeff_grid,
            print_screen=3)
myShocks = Shocks(myPars)
state_sols = solver.solve_lc(myPars)

intial wage coeff grid
[[ 1.e+01  0.e+00 -0.e+00  0.e+00]
 [ 2.e+01  5.e-01 -2.e-02  0.e+00]
 [ 3.e+01  5.e-01 -2.e-02  0.e+00]]
state_sols shape (5, 3, 2, 1, 50)
solved period 49 of 50
solved period 48 of 50
solved period 47 of 50
solved period 46 of 50
solved period 45 of 50
solved period 44 of 50
solved period 43 of 50
solved period 42 of 50
solved period 41 of 50
solved period 40 of 50
solved period 39 of 50
solved period 38 of 50
solved period 37 of 50
solved period 36 of 50
solved period 35 of 50
solved period 34 of 50
solved period 33 of 50
solved period 32 of 50
solved period 31 of 50
solved period 30 of 50
solved period 29 of 50
solved period 28 of 50
solved period 27 of 50
solved period 26 of 50
solved period 25 of 50
solved period 24 of 50
solved period 23 of 50
solved period 22 of 50
solved period 21 of 50
solved period 20 of 50
solved period 19 of 50
solved period 18 of 50
solved period 17 of 50
solved period 16 of 50
solved period 15 of 50
solved period 14 of 50
solved pe

In [110]:
asset_ind = 3
fe_ind = 0
h_ind = 1
nu_ind = 0
for j in range(myPars.J):
    print(f"For j={j}: {state_sols['lab'][asset_ind, fe_ind, h_ind, nu_ind, j]}")

For j=0: 0.0072515513502333295
For j=1: 0.007414517653756655
For j=2: 0.007584293360676551
For j=3: 0.0077613129694165655
For j=4: 0.007946048747692567
For j=5: 0.00813901492761203
For j=6: 0.008340772472625001
For j=7: 0.008551934509384039
For j=8: 0.00877317253528883
For j=9: 0.00900522353409917
For j=10: 0.00924889815846287
For j=11: 0.009505090170780061
For j=12: 0.009774787374103344
For j=13: 0.010059084314851597
For j=14: 0.010359197101705154
For j=15: 0.01067648076372293
For j=16: 0.011012449670220472
For j=17: 0.011368801661555863
For j=18: 0.011747446702182543
For j=19: 0.012150541076598713
For j=20: 0.012580528420847795
For j=21: 0.013040189238624371
For j=22: 0.013532701021924625
For j=23: 0.014061711723946208
For j=24: 0.01463143017686594
For j=25: 0.015246738196030769
For j=26: 0.015913330691564528
For j=27: 0.016637892305467812
For j=28: 0.01742832218753445
For j=29: 0.018294022944160094
For j=30: 0.019246276202640612
For j=31: 0.020298736675131514
For j=32: 0.02146809076

In [83]:
sim_lc = simulate.sim_lc(myPars, myShocks, state_sols)

In [84]:
print(sim_lc['lab'])

[[[[[ 3.60000000e-01  3.60000000e-01  3.60000000e-01 ...
      3.60000000e-01  3.60000000e-01 -9.99900000e+03]
    [ 3.60000000e-01  3.60000000e-01  3.60000000e-01 ...
      3.60000000e-01  3.60000000e-01 -9.99900000e+03]
    [ 3.60000000e-01  3.60000000e-01  3.60000000e-01 ...
      3.60000000e-01  3.60000000e-01 -9.99900000e+03]
    ...
    [ 3.60000000e-01  3.60000000e-01  3.60000000e-01 ...
      3.60000000e-01  3.60000000e-01 -9.99900000e+03]
    [ 3.60000000e-01  3.60000000e-01  3.60000000e-01 ...
      3.60000000e-01  3.60000000e-01 -9.99900000e+03]
    [ 3.60000000e-01  3.60000000e-01  3.60000000e-01 ...
      3.60000000e-01  3.60000000e-01 -9.99900000e+03]]]


  [[[ 4.00000000e-01  4.00000000e-01  4.00000000e-01 ...
      4.00000000e-01  4.00000000e-01 -9.99900000e+03]
    [ 4.00000000e-01  4.00000000e-01  4.00000000e-01 ...
      4.00000000e-01  4.00000000e-01 -9.99900000e+03]
    [ 4.00000000e-01  4.00000000e-01  4.00000000e-01 ...
      4.00000000e-01  4.00000000e-01 -9.999

In [111]:
run.output(myPars, state_sols, sim_lc)

 Consumption
log Consumption
 Labor
log Labor
 Assets
log Assets
 Wage
log Wage
 Labor Income
log Labor Income
